### ISSUE TITLE
Specifying Custom Override Filenames and Directory

### ISSUE THREAD

**Issue by pluttrell** [stevesaliman/gradle-properties-plugin#15]
I have two questions or feature requests towards a goal I've always tried to achieve with build scripts that I've authored: Make them work out of the box with as little custom configuration as absolutely necessary.

1: Is there a way to specify tokens in file names? What we'd like to do is to be able to utilize the hostname and login user name in the specification of the override property file. So for the `gradle-${environmentName}.properties` file that is searched in step 2 of the plugin's property loading phase, we'd like the ability to utilize the machine's hostname or the login user's name in place of `environmentName` and have it defined in the gradle script itself. I know you can do this currently by passing custom command line arguments every time you build.... But allowing these overrides, enables us to check each hostname/username specific file into a repo, which has two advantages: 1) It  enables less work to get environments up faster without impacting other developers machines (which is particularly helpful if you have a number of branches of the same repo checked out to the same machine at a time and actively swap between them). And 2) it allows us to version control common machine files for environments *with better specificity* and without manual setup as required with passing these via command line arguments. And 3) makes running Gradle easier as you don't need to pass the command line overrides.

2: Is there a way to specify a sub-directory for the `gradle-${environmentName}.properties` file that is searched in step 2 of the plugin's property loading phase? If not, I'd like to request that one is added to the DSL for configuration in the script. The reasoning I'm requesting this is we prefer to commit our environment specific files and without the ability to specify a sub directory, the number of files in the root of our project will grow unnecessarily. 

ANT can do both of these currently as follows: `<property file="build-properties/${user.name}.properties"/>` and `<property file="build-properties/${hostname}.properties"/>`. If this is not currently possible, I'd like to request that it be added.

Thanks.

**Comment by stevesaliman** [comment]
I just uploaded the latest 1.4.3-SNAPSHOT release to the Maven Central snapshot repository.  This version has a way to specify the location of the environment specific files.  Sorry for the lengthy delay, I haven't had a lot of spare time lately... 

If you set a value for the ```environmentFileDir``` property, the plugin will use that directory to find the ```gradle-${environmentName}.properties``` file.  The directory specified should be relative to the project directory, and it will only be used for the environment specific file.  All other files will still be searched for in the usual location.  

As for using hostnames or other tokens in the filename, you could use the hostname as the environment name.  You could set this on the command line with ```gradle -PenvironmentName=$HOSTNAME``` or something similar, or you could add code to ```build.gradle``` that sets the environment name based on the hostname or username before the properties plugin is applied.  That way, you could have properties files named ```gradle-mydevhost.properties```, ```gradle-mytesthost.properties```, etc.  One challenge you might have with this approach is how to deal with individual developer's machines.  Instead of each developer having a file named ```gradle-local.properties```, they would each have to create a file for their particular machine.

I'd be interested in hearing how this is working for you before I release the production version.

**Comment by stevesaliman** [comment]
I just released version 1.4.3 to production.  It is available on the Gradle plugin portal, and will be on Maven Central shortly.
