### ISSUE TITLE
UPPER_CASE properties handled 'unexpectedly'

### ISSUE THREAD

**Issue by DALDEI** [stevesaliman/gradle-properties-plugin#22]
Likely this isn't a 'bug' but would benefit from mentioning in the docs.
I converted a project to use gradle-properties-plugin.  The properties were all upper case like SYSTEM_NAME=name   etc.
( not the gradle standard )

It did work (yea!) but when I did a 'gradle properties' I noticed the additional properties added were very odd until I realized the camelCase conversion.   

SYSTEM_NAME was replicated something like as .s.y.s.t.e.m..n.a.m.e  (leading dot)
It might be good to mention to stick with either ant (lower.case.dotted) or gradle (camelCase) property names. Or ... a feature might be to recognize this fairly common convention and leave all upper case properties as-is.   A safe rule might be simply if a property starts with an upper case letter then dont add the additional variant.  Neither  gradle nor ant conventions use properties that start with an upper case.  Considering that the conversions are for convenience, missing some is less likely to cause a hidden bug later - it would show up early in development.  Adding unexpected properties is more likely to cause problems then solve them, and less likely to be discovered early.

-David

**Comment by stevesaliman** [comment]
I agree that changing SYSTEM_NAME to .s.y.s.t.e.m..n.a.m.e in the filterTokens is kind of silly.  I like the idea of preserving variables that are all upper case, so I'm going to add a feature to do that.  I just haven't decided if I'm going to target properties that are all caps, or properties that simply start out with a capital letter.

Thank you for the suggestion.

**Comment by stevesaliman** [comment]
This has been fixed in version 1.4.4 of the plugin.  I decided that when I copy a camel case property to dot notation, it needs to start with a lower case letter to be considered camel case.  This means that upper case properties will not be copied to the filter tokens as dot notation, and neither will properties that start with an underscore.  

The documentation already talked about the filterTokens, and the dot notation copies that get made.  I've added a mention of upper case properties to it.
